name: GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    # cronjob that triggers every day at 3PM UTC
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Checkout YimMenu
        uses: actions/checkout@v3
        with:
          repository: YimMenu/YimMenu
          path: YimMenu
          fetch-depth: 0

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Generate Changelog
        run: |
          mv .github/changelog_generator.js .
          mv .github/cliff.toml .
          mv .github/replace.js .
          git log  --format="%cs#%H" | node changelog_generator.js
          cp changelog.md changelog.txt
          npx --yes showdown makehtml -i changelog.md -o changelog_from_md.html
          node replace.js
          rm -rf *.js *.template .github/ changelog_from_md.html
          cp changelog.html changelog

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
